project: linebot-test1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /worker
  script: main.app
  login: admin
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: linebot-test1:us-central1
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: 32103210
# [END env_variables]
